# Writing Excuses Season 8 

- [ ] 8.1: Microcasting 
- [ ] 8.2: Hero’s Journey 
- [ ] 8.3: Pets 
- [ ] 8.4: Side-Character Arcs 
- [ ] 8.5: Breaking the Rules 
- [ ] 8.6: Retellings and Adaptations 
- [ ] 8.7: Cliffhangers and Icebergs with Robison Wells 
- [ ] 8.8: Writing and Personal Health 
- [ ] 8.9: Brainstorming with Howard 
- [ ] 8.10: Brainstorming With Howard Again 
- [ ] 8.11: Abnormal Psychology 
- [ ] 8.12: Project in Depth — Deus ex Nauseum 
- [ ] 8.13: Fake It Till You Make it 
- [ ] 8.14: Brainstorming with Brandon 
- [ ] 8.15: Narrative Rhythm 
- [ ] 8.16: Brainstorming with Brandon Again 
- [ ] 8.17: Microcasting 
- [ ] 8.18: Blocking 
- [ ] 8.19: Writing and Convention Culture 
- [ ] 8.20: The Short Story, with Mary Robinette Kowal 
- [ ] 8.21: What the Avengers did Right 
- [ ] 8.22: Pre-writing with E.J. Patten 
- [ ] 8.23: Microcasting 
- [ ] 8.24: Project in Depth–Kiss Me Twice 
- [ ] 8.25: Middle Grade with E.J. Patten 
- [ ] 8.26: Space Opera 
- [ ] 8.27: Chapter Breakdowns 
- [ ] 8.28: Your First Contract 
- [ ] 8.29: Out of Excuses Retreat Q&A #1 
- [ ] 8.30: Writing Reluctant Characters 
- [ ] 8.31: Combining Dialogue, Blocking, and Description 
- [ ] 8.32: Microcasting 
- [ ] 8.33: Making Non-Human Characters Relatable 
- [ ] 8.34: Survivorship Bias 
- [ ] 8.35: Digging Yourself Out of Holes with Jeph Jacques 
- [ ] 8.36: Transitioning Characters in Prominence 
- [ ] 8.37: When Fail Happens in Your Career 
- [ ] 8.38:Out of Excuses Retreat Q&A #2 
- [ ] 8.39: Dystopian Fiction with Cherie Priest 
- [ ] 8.40: Publishing with Bill Schafer 
- [ ] 8.41: Out of Excuses Retreat Microcasting 
- [ ] 8.42: The Internal Heckler vs. The Internal Editor 
- [ ] 8.43: Realistic Melee Fighting with Wesley Chu 
- [ ] 8.44: Talking Publishing with Tom Doherty 
- [ ] 8.45: Gencon Q&A With Wesley Chu 
- [ ] 8.46: Editing with Aeryn Rudel 
- [ ] 8.47: Roguishness with Scott Lynch 
- [ ] 8.48: Long-Form Storytelling with Sam Logan 
- [ ] 8.49: Hard Social Science Fiction with Joel Shepherd 
- [ ] 8.50: Q&A with Mercedes Lackey 
- [ ] 8.51: Creative non-fiction with Mette Ivie Harrison 
- [ ] 8.52: You Think You Don’t Have Time to Write, with Mette Ivie Harrison 
